import {
  ARC_TESTNET_CHAIN_ID,
  ERC8004_IDENTITY_REGISTRY,
  ERC8004_REPUTATION_REGISTRY,
  ERC8004_VALIDATION_REGISTRY,
  ERC8183_CONTRACT_ADDRESS,
} from "./arc";
import type { WorkNetState } from "./types";

const now = "2026-05-24T04:00:00.000Z";

export const seedState: WorkNetState = {
  activeProfileId: "profile_client_ada",
  profiles: [
    {
      id: "profile_client_ada",
      displayName: "Ada Kim",
      handle: "ada-builds",
      role: "client",
      bio: "Product lead funding tight technical outcomes on Arc.",
      walletAddress: "0x8C4b8b2f9f76D0A4E4b6645d6F3a9A9b28d2Ab01",
      countryCode: "US",
      timezone: "America/New_York",
      skills: ["Product strategy", "Payments", "USDC", "Procurement"],
      hourlyRateUsdcUnits: 120000000,
      availability: "limited",
      portfolio: [],
      totalEarnedUsdcUnits: 0,
      totalSpentUsdcUnits: 2480000000,
      completedJobsCount: 9,
      ratingAvg: 4.9,
      ratingCount: 9,
      isVerified: true,
      isBlocked: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "profile_worker_mira",
      displayName: "Mira Tan",
      handle: "mira-ships",
      role: "worker",
      bio: "Full-stack engineer focused on payment, wallet, and indexing integrations.",
      walletAddress: "0x9c1f4D6eB28cA8c44d0eC08f384A5c446D42c112",
      countryCode: "ID",
      timezone: "Asia/Jakarta",
      skills: ["TypeScript", "Solidity", "Indexer", "viem", "React", "USDC", "Payments"],
      hourlyRateUsdcUnits: 85000000,
      availability: "open",
      portfolio: [
        {
          id: "portfolio_mira_indexer",
          title: "USDC settlement indexer",
          url: "https://example.com/work/usdc-indexer",
          description: "Built a viem-based indexer that tails ERC-8183 escrow events and reconciles to USDC settlements.",
        },
        {
          id: "portfolio_mira_dashboard",
          title: "On-chain payments dashboard",
          url: "https://example.com/work/payments-dashboard",
          description: "React + Next.js dashboard surfacing escrow state and settlement TX explorer links.",
        },
      ],
      totalEarnedUsdcUnits: 1715000000,
      totalSpentUsdcUnits: 0,
      completedJobsCount: 14,
      ratingAvg: 4.8,
      ratingCount: 13,
      isVerified: true,
      isBlocked: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "profile_agent_owner",
      displayName: "Rafi Systems",
      handle: "rafi-agents",
      role: "agent_owner",
      bio: "Runs specialized code review and dataset QA agents.",
      walletAddress: "0x4cE92f2d7Dd945d35f90F461A4fB28492A6F61A0",
      countryCode: "SG",
      timezone: "Asia/Singapore",
      skills: ["AI agents", "LLM ops", "Dataset QA", "Code review"],
      hourlyRateUsdcUnits: 95000000,
      availability: "open",
      portfolio: [
        {
          id: "portfolio_rafi_lintsmith",
          title: "LintSmith agent — static review for payments",
          url: "https://example.com/agents/lintsmith",
          description: "Production AI agent doing static TypeScript + Solidity review with patch proposals.",
        },
      ],
      totalEarnedUsdcUnits: 690000000,
      totalSpentUsdcUnits: 0,
      completedJobsCount: 7,
      ratingAvg: 4.7,
      ratingCount: 7,
      isVerified: true,
      isBlocked: false,
      createdAt: now,
      updatedAt: now,
    },
  ],
  agents: [
    {
      id: "agent_lintsmith",
      ownerProfileId: "profile_agent_owner",
      name: "LintSmith",
      slug: "lintsmith",
      description: "Static analysis agent for TypeScript, Solidity, and payment integration regressions.",
      capabilities: ["TypeScript audit", "Solidity review", "CI triage", "Patch proposals"],
      agentWalletAddress: "0xCA7F29e468d53290f690f73e6cAFaE2f6bB47333",
      metadataUri: "ipfs://bafy-worknet-lintsmith",
      arcAgentId: "8004001",
      identityRegistryAddress: ERC8004_IDENTITY_REGISTRY,
      reputationRegistryAddress: ERC8004_REPUTATION_REGISTRY,
      validationRegistryAddress: ERC8004_VALIDATION_REGISTRY,
      registrationTxHash: "0x7100b2ec7100b2ec7100b2ec7100b2ec7100b2ec7100b2ec7100b2ec7100b2ec",
      reputationScore: 92,
      jobsCompleted: 7,
      isPublic: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  jobs: [
    {
      id: "job_bridge_health",
      clientProfileId: "profile_client_ada",
      providerProfileId: "profile_worker_mira",
      actorType: "human",
      title: "Build Arc bridge funding checklist",
      brief:
        "Create a launch-ready checklist for payer funding flows that moves USDC from Ethereum or Base into Arc and catches the common wallet setup failures.",
      acceptanceCriteria:
        "Checklist covers chain setup, USDC decimal handling, App Kit Bridge handoff, funding receipt verification, and user-facing failure copy.",
      deliverableFormat: "Markdown brief and QA checklist URL",
      category: "Payments",
      tags: ["Arc", "USDC", "Bridge", "QA"],
      budgetUsdcUnits: 125000000,
      platformFeeBps: 100,
      deadlineAt: "2026-05-31T16:00:00.000Z",
      status: "funded",
      evaluatorAddress: "0x8C4b8b2f9f76D0A4E4b6645d6F3a9A9b28d2Ab01",
      providerAddress: "0x9c1f4D6eB28cA8c44d0eC08f384A5c446D42c112",
      arcChainId: ARC_TESTNET_CHAIN_ID,
      arcContractAddress: ERC8183_CONTRACT_ADDRESS,
      arcJobId: "1207",
      descriptionHash: "0xa4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4a4b4",
      createTxHash: "0xa111c0dea111c0dea111c0dea111c0dea111c0dea111c0dea111c0dea111c0de",
      setBudgetTxHash: "0xb111c0deb111c0deb111c0deb111c0deb111c0deb111c0deb111c0deb111c0de",
      approveTxHash: "0xc111c0dec111c0dec111c0dec111c0dec111c0dec111c0dec111c0dec111c0de",
      fundTxHash: "0xd111c0ded111c0ded111c0ded111c0ded111c0ded111c0ded111c0ded111c0de",
      lastIndexedBlock: 1960482,
      createdAt: "2026-05-20T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job_agent_eval",
      clientProfileId: "profile_client_ada",
      providerAgentId: "agent_lintsmith",
      actorType: "agent",
      title: "Evaluate escrow contract happy path",
      brief:
        "Run a focused review of the ERC-8183 integration path and produce risk-ranked findings for create, budget, fund, submit, and complete calls.",
      acceptanceCriteria:
        "Findings include severity, exact function or screen, reproduction details, and a concrete patch recommendation.",
      deliverableFormat: "Structured JSON report",
      category: "Security",
      tags: ["ERC-8183", "Agent", "Review"],
      budgetUsdcUnits: 350000000,
      platformFeeBps: 100,
      deadlineAt: "2026-06-03T16:00:00.000Z",
      status: "submitted",
      evaluatorAddress: "0x8C4b8b2f9f76D0A4E4b6645d6F3a9A9b28d2Ab01",
      providerAddress: "0xCA7F29e468d53290f690f73e6cAFaE2f6bB47333",
      arcChainId: ARC_TESTNET_CHAIN_ID,
      arcContractAddress: ERC8183_CONTRACT_ADDRESS,
      arcJobId: "1219",
      descriptionHash: "0xe4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4",
      createTxHash: "0xe111c0dee111c0dee111c0dee111c0dee111c0dee111c0dee111c0dee111c0de",
      setBudgetTxHash: "0xf111c0def111c0def111c0def111c0def111c0def111c0def111c0def111c0de",
      approveTxHash: "0xab11c0deab11c0deab11c0deab11c0deab11c0deab11c0deab11c0deab11c0de",
      fundTxHash: "0xbc11c0debc11c0debc11c0debc11c0debc11c0debc11c0debc11c0debc11c0de",
      submitTxHash: "0xcd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0de",
      lastIndexedBlock: 1961119,
      createdAt: "2026-05-21T13:30:00.000Z",
      updatedAt: now,
    },
    {
      id: "job_open_indexer",
      clientProfileId: "profile_client_ada",
      actorType: "human",
      title: "Implement deterministic event backfill",
      brief:
        "Build a Node + viem worker that resumes from the last processed Arc block and syncs ERC-8183 job events into Supabase.",
      acceptanceCriteria:
        "Worker stores block/log ordering, idempotently inserts events, updates job statuses, and documents retry behavior for deterministic finality.",
      deliverableFormat: "Pull request URL",
      category: "Indexing",
      tags: ["Viem", "Supabase", "Events"],
      budgetUsdcUnits: 500000000,
      platformFeeBps: 100,
      deadlineAt: "2026-06-08T16:00:00.000Z",
      status: "open",
      evaluatorAddress: "0x8C4b8b2f9f76D0A4E4b6645d6F3a9A9b28d2Ab01",
      arcChainId: ARC_TESTNET_CHAIN_ID,
      createdAt: "2026-05-23T08:00:00.000Z",
      updatedAt: now,
    },
  ],
  applications: [
    {
      id: "application_mira_indexer",
      jobId: "job_open_indexer",
      applicantProfileId: "profile_worker_mira",
      actorType: "human",
      pitch:
        "I can ship the worker with viem log decoding, Supabase upserts, and a dry-run mode for replay testing.",
      proposedBudgetUsdcUnits: 500000000,
      proposedDeadlineAt: "2026-06-07T16:00:00.000Z",
      status: "pending",
      createdAt: "2026-05-23T09:40:00.000Z",
      updatedAt: "2026-05-23T09:40:00.000Z",
    },
  ],
  submissions: [
    {
      id: "submission_agent_eval",
      jobId: "job_agent_eval",
      submitterAgentId: "agent_lintsmith",
      notes: "Risk-ranked review complete. Two medium issues and one low issue found.",
      deliverableUrl: "https://example.com/worknet/erc8183-review.json",
      deliverableSha256: "0xdadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadada",
      deliverablePayload: {
        jobId: "job_agent_eval",
        submissionId: "submission_agent_eval",
        urls: ["https://example.com/worknet/erc8183-review.json"],
      },
      deliverableHashBytes32: "0xdadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadada",
      status: "submitted",
      submitTxHash: "0xcd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0de",
      createdAt: "2026-05-24T02:20:00.000Z",
      updatedAt: "2026-05-24T02:20:00.000Z",
    },
  ],
  reviews: [
    {
      id: "review_mira_payments",
      jobId: "job_agent_eval",
      reviewerProfileId: "profile_client_ada",
      submissionId: "submission_agent_eval",
      rating: 5,
      reviewText:
        "Mira shipped the indexer ahead of the deadline and pre-empted two settlement edge cases we hadn't even scoped. Strong communication.",
      createdAt: "2026-04-12T14:05:00.000Z",
    },
    {
      id: "review_rafi_lintsmith",
      jobId: "job_agent_eval",
      reviewerProfileId: "profile_client_ada",
      submissionId: "submission_agent_eval",
      rating: 5,
      reviewText:
        "LintSmith caught a subtle approve/funded race condition. Patch proposal landed cleanly, payment released same day.",
      createdAt: "2026-05-02T09:30:00.000Z",
    },
  ],
  aiEvaluations: [
    {
      id: "evaluation_agent_eval",
      jobId: "job_agent_eval",
      submissionId: "submission_agent_eval",
      model: "ai-evaluator-draft",
      score: 88,
      verdict: "pass",
      summary:
        "Deliverable satisfies the requested happy path coverage and includes actionable findings. Reviewer should confirm the budget setter assumption before release.",
      rubric: {
        completeness: 92,
        specificity: 86,
        reproducibility: 84,
      },
      rawOutput: {},
      createdAt: "2026-05-24T02:22:00.000Z",
    },
  ],
  transactions: [
    {
      id: "tx_job_agent_submit",
      jobId: "job_agent_eval",
      chainId: ARC_TESTNET_CHAIN_ID,
      blockchain: "ARC-TESTNET",
      contractAddress: ERC8183_CONTRACT_ADDRESS,
      method: "submit",
      txHash: "0xcd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0de",
      status: "confirmed",
      blockNumber: 1961119,
      metadata: { jobId: "1219" },
      createdAt: "2026-05-24T02:20:00.000Z",
      confirmedAt: "2026-05-24T02:20:01.000Z",
    },
  ],
  events: [
    {
      id: "event_job_agent_submit",
      chainId: ARC_TESTNET_CHAIN_ID,
      blockchain: "ARC-TESTNET",
      contractAddress: ERC8183_CONTRACT_ADDRESS,
      eventSignature: "Submitted(uint256,bytes32)",
      txHash: "0xcd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0decd11c0de",
      blockNumber: 1961119,
      logIndex: 4,
      decoded: { jobId: "1219", deliverableHash: "0xdadadada..." },
      createdAt: "2026-05-24T02:20:01.000Z",
    },
  ],
  notifications: [
    {
      id: "notification_submission",
      profileId: "profile_client_ada",
      type: "submission",
      title: "Deliverable submitted",
      body: "LintSmith submitted the ERC-8183 review for approval.",
      href: "/jobs/job_agent_eval/review",
      createdAt: "2026-05-24T02:22:00.000Z",
    },
  ],
  jobMessages: [],
  jobInvitations: [],
  savedJobs: [],
  applicationOverlays: [],
};
